language: node_js
node_js: node
cache:
  directories:
  - node_modules
branches:
  only:
  - master
env:
  secure: f13FkJUpuUi1Ku3hsnjBrapWNyzOHCAO5HAzSdL2CAo1VGYsqsbJFMLd2anG81XPDr3boK5vy4gZqM0Rrk5Eo8FrqCEuola1n6BOlU+8yKFMfp6cyrVQMTVENQ+Vdhq+bTcwg+jcmgdWc2LFU5W3oe/Kg1rQg0WVEESNMtiJAQ4y0exvkXBMjpyBHgmKRbsd+YJ24I1Wu1B6D0d2VhrwPOy5AUYO4YaFgGaDlgxM/GbUZGbZVJpua0S5fHu9cFZflL0CW8wtpD0uwITs09z5N+a12jFOYSKx2wC2j+LAj/b205p88W8y2FUFJsziouNze75f/2Cr0VTm8JczVsJKGD1B5PztVNZ7P0zWOelojPMo+J7NNIVYKIu82eCgjCejnl4Ll0S8YgJMa31r4CyBTptwU7MWDYP6v3Wf/I0o5aDMgMpO7zCGyiDXnzuDZlzkzwkUxoY3ynoQLHakLL2566yZ+h1KAS5KD8V6rkqdBcGY7JxFwt/5ANKclaX+GK6EdWB4wUIXzKage0QUE3+ahxShOvs2fcClz+4vShWst6S24tdOmMfnU+vnVgBNTqeTxOTGUgiK/TRV7Bxg0DNoVtORb2JKdzOMmMM65XSMmgjOPn4cgKEOkAgIuZgzZYP34uTj36HF7UonIthWzjkBeTTEan9tqC7XZSuALx26BwM=
