language: node_js
node_js: node
cache:
  directories:
  - node_modules
branches:
  only:
  - master
env:
  secure: lFA7CDw3w0cI+HtrDZSbo337sWkZ33oS45MqQ8mQeLmyZzfmnuZmq4KO92X6HPxXGF0j+N4m54ewlMub7bAh6gXjuD37fOfwtcHVQ2qltHrRr7oTa6b1A6BKPstx6qEdCV0ITh1/TuBKRGam4Ys2tI7kJmK9J1zLeaWVgN4ttfmplSqhl3Uo/2cJC6F9TIlnbS+NkaCBKmKZWX7B6Nfp8X3VdWxWp5vpvYcKYB1nNhPtb2YKOyWHqTXF5AWW76PmBPR4kRf+5E/1/jlncMiGHMktVgbUtdW92Hd2l3BJWrt7nqiVrcMrovCXdS2Z5J6Xv+5jvvT2aEKzm+gUi8cgaL3Mtowhy/l+uDkI0FzDbimuvMQmfNoKnRyRgUazFJxG22iS5TW4z5iFI7SXqK1bXz8tyJlUialCXceXqUDAiWC3pJmSEMbtvNkJl6RllvVBOKeUb0cagmCpCOwxnwUVlhr3TMMI1SAp5w6hXaQCVuzu61mQwW6CWNwTxpPFTKvg7jM4zd+ZyOC2AIN6RtFGPmB8aLDom2CBEGcseBxdCrH4d/0o4XH3UaqOpA08/TQ3nftq4pnKpW4dsURrkfZrKEYfsONKhnB7v07VnqGFfuoilwengC/70eQ8/aNxkctIt0yNHiJZKEGOBKeuwXfDOqbht8x3XNFholPTolHdWrc=
