language: node_js
node_js: node
cache:
  directories:
  - node_modules
branches:
  only:
  - master
env:
  global:
    secure: R4EuMQNhrQ3yT//OGnY8NsDsuVXWaP5plVBD2SVsUpep3nICWsQCuci7Mfx5wpBIPxY98Zuge6JSYUpZsC90NLH6Xmm2hnWkFo786OzNTdhvXnMdenBJaYg4WjlqN2RwO/e6ZreKSoeWtP9ZZsXktF3B90TfKrDn6VHvKUC5LBBtLK67UuFg2fAczlcR2xiDbF4vk/kHY96bPyQMlHFpt0P14qyY31o+s0w9+wdDOWH/uQ7G7Y5qQGyRkW3IpzST36z6Cvp1F9/t1P1Acu1aIn6/69z/Xn5OTrtw+XH8F8fCvUpH6TgQMOi8JpONUh51FOBhnySG8N5OmIleoKo8LShf2M30SnJ13J2NyLQkq71oTfSnBjKwW/Fz/WYE+IXXl3iv4OtjvYOdZNmHQYMzWdIkMXWB8BF9/7di7JmjR3cGyYeO62opNVJsCprcnPEKlAMTF3RWyxJ7EggnUGuOvCyoohE+8dU3LTnjqPfNONG3wsa/KZI2J3xiqBd3a24GfMX4XmK+6ZirR+gi5njflgW1V+5H0hwwLKEJf+l8WOWNqcxLbcRfnGcdO1k8IyTdNuitah9YqqliA3Dlr3PadcE+I7nE2QgG9u7eLPLCDwIJbXKamOtwbrh7wuupto0QyTPbQua+3tYfBFcfNh0OD6v26cP1S5tN77EJdn5k3eE=
