module.exports = {
  GITHUB_API_USERS: 'https://api.github.com/users',
  GITHUB_API_TEAMS: 'https://api.github.com/orgs/hackreactor/teams',
  SFDC_OPPTY_RECORD_ID: '012j0000000qVAP',
  SFDC_SELECT_QUERY: `Id, Student__c, Student__r.Name,
  Student__r.Email, Student__r.Secondary_Email__c, Campus_Formatted__c,
  Student__r.Github_Username__c, Course_Start_Date_Actual__c, Product_Code__c,
  StageName, Separation_Status__c, Separation_Type__c, Separation_Reason__c,
  Last_Day_Of_Attendance__c, Last_Day_of_Attendance_Acronym__c,
  Official_Withdrawal_Date__c, Student__r.Preferred_First_Name__c, Student__r.Birthdate,
  Student__r.Phone, Student__r.MailingAddress, Student__r.Emergency_Contact_Name__c,
  Student__r.Emergency_Contact_Phone__c, Student__r.Emergency_Contact_Relationship__c,
  Student__r.Tshirt_Size__c, Student__r.T_Shirt_Fit__c, Student__r.Highest_Degree__c,
  Student__r.gender__c, Student__r.Race__c, Student__r.EthnicityNew__c,
  Student__r.Identify_as_LGBTQ__c, Student__r.US_Veteran__c, Student__r.Dependent_of_Veteran__c,
  Student__r.US_Citizen_or_Permanent_Resident__c, Student__r.Hoodie_Size__c,
  Student__r.Address_While_in_School__c, Student__r.Allergies__c, Student__r.OtherAddress,
  Student__r.Student_Funding_1__c, Student__r.Student_Funding_1_Stage__c, Payment_Option__c`,
  LEARN_API_COHORTS: ' https://learn-2.galvanize.com/api/v1/cohorts',
};
